###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
spring:
  application:
    ####注册中心本应用名称
    name: config-server
  cloud:
    config:
      server:
        git:
          ###git环境地址
          uri: https://github.com/bhsdy/config.git
          ####搜索目录
          search-paths: dev
      ####读取哪个分支
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: finance
    password: finance
####端口号
server:
  port: 8888

###开启bus刷新
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","bus-refresh"]

